#import "./TestFragment.gql"
#import "../../Students/StudentFragment.gql"

query GetTestById ($id: uuid!) {
    Tests_by_pk(id: $id) {
        ...Test,
        Students_Tests {
            student_id
        }
    }
    Students {
        ...Student
    }
}